#!/bin/sh
# Stands in for `pacman -Sl <repos>` in dev mode and in the tests: the same
# "<repo> <name> <version> [installed]" lines, with no pacman on the machine.
cat <<'LIST'
core coreutils 9.11-2 [installed]
core bash 5.3-1 [installed]
extra npm 11.0.0-1 [installed]
extra nodejs 26.5.0-1 [installed]
extra restic 0.18.1-1 [installed]
LIST
