#!/usr/bin/env bash
# Capture shell/tests/fixtures/wire/* from the REAL daemon.
#
# The point of the wire fixtures is that MoatModel.js is tested against output
# moatd actually produced, not against hand-written examples of what it ought
# to produce. So they have to be regenerated by running the daemon, and this is
# the script that does it. Run it whenever the alert record or a socket
# response changes shape:
#
#     shell/tests/capture-wire-fixtures.sh
#     shell/tests/capture-wire-fixtures.sh --keep     # keep the scratch dir
#
# Unprivileged. No root, no /etc, no /run, no Tetragon, nothing installed:
# every path is overridden on the command line the way moatd/dev-run.sh does
# it, the "Tetragon export" is gen-export-log.py's synthetic JSON, and the
# provenance database is moatd/testdata/pacman-local.
#
# Two substitutions are applied to the captures, and only two: the scratch
# directory becomes the installed paths from CONTRACT section 2, and the socket
# group becomes `moat`. Everything else is byte-for-byte what the daemon wrote.
set -euo pipefail

HERE=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
ROOT=$(cd -- "$HERE/../.." && pwd)
MOATD_DIR=$ROOT/moatd
OUT=$HERE/fixtures/wire

MOATD_BIN=${MOATD_BIN:-$MOATD_DIR/target/debug/moatd}
MOATCTL_BIN=${MOATCTL_BIN:-$MOATD_DIR/target/debug/moatctl}

KEEP=0
[[ ${1:-} == --keep ]] && KEEP=1

if [[ ! -x $MOATD_BIN || ! -x $MOATCTL_BIN ]]; then
	echo "building moatd" >&2
	(cd "$MOATD_DIR" && cargo build --quiet)
fi

D=$(mktemp -d -t moat-wire-XXXXXX)
FAKE_HOME=/home/moattest
SOCK=$D/run/control.sock
LOG=$D/tetragon.log
DAEMON_PID=""
VICTIM_PID=""

cleanup() {
	local rc=$?
	# Every step is unconditional: `wait` on a TERMed child returns 143, and
	# under `set -e` a bare && chain here would abandon the rest of the
	# cleanup and leave the daemon running (it did, once).
	if [[ -n $VICTIM_PID ]]; then
		kill -TERM "$VICTIM_PID" 2>/dev/null || true
		wait "$VICTIM_PID" 2>/dev/null || true
	fi
	if [[ -n $DAEMON_PID ]]; then
		kill -TERM "$DAEMON_PID" 2>/dev/null || true
		wait "$DAEMON_PID" 2>/dev/null || true
	fi
	if ((rc == 0 && KEEP == 0)); then rm -rf "$D"; else echo "scratch dir: $D" >&2; fi
	exit $rc
}
trap cleanup EXIT INT TERM

mkdir -p "$D"/{policies,state,run,allowlist.d,incidents,etc}

# One fake human user. Nothing here touches the real /etc/passwd or the real
# home: the policies are rendered for /home/moattest and every event names it.
cat >"$D/passwd" <<EOF
root:x:0:0::/root:/usr/bin/bash
moattest:x:1000:1000::${FAKE_HOME}:/usr/bin/fish
nobody:x:65534:65534::/:/usr/bin/nologin
EOF

# Only two knobs move off the shipped defaults, and both are real config keys:
#   learn_min_days = 1  -- the shipped 3 means "three distinct DAYS", and the
#     daemon stamps a tuple's day from the wall clock, not from the event's
#     timestamp, so three days cannot be faked inside one run (see
#     docs/INTEGRATION.md "open issues").
#   noisy_rule_per_day = 5  -- the shipped 20 needs a 21-alert burst, which
#     would triple the size of the fixtures for no extra coverage: the guard
#     is the same code path at either threshold.
cat >"$D/etc/moat.toml" <<'EOF'
[baseline]
learn_min_days = 1
noisy_rule_per_day = 5
EOF

# ---------------------------------------------------------------- render ---
echo "==> render-policies (the real 32 templates, fake home $FAKE_HOME)"
"$MOATD_BIN" render-policies \
	--templates-dir "$ROOT/policies" \
	--out-dir "$D/policies" \
	--export-allowlist "$D/export-allowlist" \
	--home "$FAKE_HOME" | tee "$D/render.txt"
echo "    {{HOME}} left over: $(grep -rl '{{HOME}}' "$D/policies" | wc -l) file(s)"
echo "    $FAKE_HOME present in: $(grep -rl "$FAKE_HOME" "$D/policies" | wc -l) file(s)"

# ------------------------------------------------------------------ pids ---
# A real, live process stands in for the acting process of the critical
# pkg-install alert, so the incident snapshot (LEARNING 4) reads a real /proc
# instead of recording "gone". Everything else uses pids picked to be free.
# Both background children get their own output file: anything still holding
# this script's stdout keeps a `| tail` alive long after the script exits.
sleep 600 >/dev/null 2>&1 &
VICTIM_PID=$!
PID_BASE=$(python3 - <<'PY'
import os
base = 30000
while any(os.path.exists("/proc/%d" % (base + i)) for i in range(1, 1000)):
    base += 1000
print(base)
PY
)
echo "==> live stand-in pid $VICTIM_PID, synthetic pid base $PID_BASE"

: >"$LOG"

ctl() { "$MOATCTL_BIN" --socket "$SOCK" "$@"; }

echo "==> moatd run"
"$MOATD_BIN" run \
	--config "$D/etc/moat.toml" \
	--log "$LOG" \
	--state-dir "$D/state" \
	--socket "$SOCK" \
	--policies-dir "$D/policies" \
	--allowlist-dir "$D/allowlist.d" \
	--incidents-dir "$D/incidents" \
	--sandbox-flag "$D/etc/sandbox.enabled" \
	--passwd "$D/passwd" \
	--pacman-local "$MOATD_DIR/testdata/pacman-local" \
	--pacman "$MOATD_DIR/testdata/fake-pacman" \
	--tetra "$D/no-such-tetra" \
	--group "$(id -gn)" \
	--from-start >"$D/moatd.log" 2>&1 &
DAEMON_PID=$!

for _ in $(seq 1 200); do [[ -S $SOCK ]] && break; sleep 0.05; done
[[ -S $SOCK ]] || { echo "socket never appeared" >&2; exit 1; }

# ---------------------------------------------------------------- phase 1 ---
echo "==> phase 1 events"
python3 "$HERE/gen-export-log.py" --phase 1 --home "$FAKE_HOME" \
	--live-pid "$VICTIM_PID" --pid-base "$PID_BASE" >>"$LOG"
sleep 1.5

# ---------------------------------------------------------------- phase 2 ---
echo "==> baseline relearn --days 0 (close the learning window), then phase 2"
ctl baseline relearn --days 0 >"$D/relearn.txt" 2>&1 || true
python3 "$HERE/gen-export-log.py" --phase 2 --home "$FAKE_HOME" \
	--live-pid "$VICTIM_PID" --pid-base "$PID_BASE" >>"$LOG"
sleep 1.5

# ---------------------------------------------------------------- capture ---
echo "==> capture"
ALERT_CRED_PKG=$(ctl --json list --limit 200 |
	python3 -c 'import json,sys
d=json.load(sys.stdin)
for a in d["alerts"]:
    if a["rule"]=="moat-cred-cloud-credentials-read" and a.get("context")=="pkg-install":
        print(a["id"]); break')
[[ -n $ALERT_CRED_PKG ]] || { echo "no pkg-install credential alert" >&2; exit 1; }

ctl --json status >"$D/status.json"
ctl --json list --limit 200 >"$D/list.json"
ctl --json explain "$ALERT_CRED_PKG" >"$D/explain.json"
ctl --json baseline list >"$D/baseline-list.json"
ctl --json baseline export >"$D/baseline-export.json"
ctl --json receipts --last 20 >"$D/receipts.json"
ctl --json bundle "$ALERT_CRED_PKG" >"$D/bundle.json"
# after the bundle, so the incident that has one reports `bundle: true`
ctl --json incidents --last 20 >"$D/incidents.json"
BUNDLE=$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["path"])' "$D/bundle.json")
cp "$BUNDLE" "$D/bundle.md"

# An ignore + allowlist round trip, so the allowlist capture has a user entry
# next to the learned and shipped ones.
cp "$MOATD_DIR/etc/allowlist.d/omarchy-default.toml" "$D/allowlist.d/omarchy-default.toml"
ctl --json ignore "$ALERT_CRED_PKG" --scope exe --comment "wire fixture" >"$D/ignore.json"
ctl --json allowlist >"$D/allowlist.json"

# The human-readable side of the same commands, for the transcript in
# docs/INTEGRATION.md. Not fixtures -- they stay in the scratch dir, which
# --keep preserves.
{
	echo "=== moatctl status ==="; ctl status
	echo; echo "=== moatctl list ==="; ctl list --limit 40
	echo; echo "=== moatctl explain $ALERT_CRED_PKG ==="; ctl explain "$ALERT_CRED_PKG"
	echo; echo "=== moatctl allowlist ==="; ctl allowlist
	echo; echo "=== moatctl baseline list ==="; ctl baseline list
	echo; echo "=== moatctl baseline export ==="; ctl baseline export
	echo; echo "=== moatctl receipts ==="; ctl receipts --last 5
	echo; echo "=== moatctl incidents ==="; ctl incidents --last 5
	echo; echo "=== moatctl rarity $ALERT_CRED_PKG ==="; ctl rarity "$ALERT_CRED_PKG"
	echo; echo "=== moatctl digest ==="; ctl digest
} >"$D/transcript.txt" 2>&1

# The two `set` responses the panel's action handler keys on.
ctl --json set mode enforce >"$D/set-mode-no-tetra.json" || true
ctl --json set mode monitor >/dev/null || true
ctl --json set sandbox on >"$D/set-sandbox.json"
ctl --json set sandbox off >/dev/null

kill -TERM "$DAEMON_PID"; wait "$DAEMON_PID" 2>/dev/null || true; DAEMON_PID=""
cp "$D/state/alerts.jsonl" "$D/alerts.jsonl"

# ------------------------------------------------------------ substitute ---
# CONTRACT section 2 paths, and the socket group the package creates.
mkdir -p "$OUT"
for f in alerts.jsonl status.json list.json explain.json allowlist.json ignore.json \
	set-mode-no-tetra.json set-sandbox.json baseline-list.json baseline-export.json \
	receipts.json incidents.json bundle.json bundle.md; do
	sed -e "s#$D/state#/var/lib/moat#g" \
		-e "s#$D/allowlist.d#/etc/moat/allowlist.d#g" \
		-e "s#$D/policies#/run/moat/policies#g" \
		-e "s#$D/incidents#/var/lib/moat/incidents#g" \
		-e "s#$D/etc#/etc/moat#g" \
		-e "s#$D/run#/run/moat#g" \
		-e "s#$D/no-such-tetra#/usr/bin/tetra#g" \
		-e "s#$D#/var/lib/moat#g" \
		-e "s#\"socket_group\": \"$(id -gn)\"#\"socket_group\": \"moat\"#g" \
		-e "s#group $(id -gn)#group moat#g" \
		"$D/$f" >"$OUT/$f"
done

echo
echo "wrote $(ls "$OUT" | wc -l) fixtures into $OUT"
ls -l "$OUT"
